global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using BindBox.Models;
global using BindBox.Impl;
global using BindBox.DAO;
global using BindBox.EF;
global using Microsoft.AspNetCore.Mvc;